font_size 12.0
url_color #eb5e28
background #252422

# BEGIN_KITTY_FONTS
font_family      family="CodeNewRoman Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
