wallpaper {
  monitor =
  path = ~/wallpapers/
  fit_mode = cover
  recursive = true
  order = random
  timout = 3600
}

wallpaper {
  monitor =
  path = ~/wallpapers/livre.png
  fit_mode = cover
}

splash = false
